! smc.f90 - Fortran interface to SparseMatrixColorings.jl
!
! Generated by interfaces/scripts/generate_header.jl from the same table as
! smc.h -- do not edit by hand, edit the generator instead.
!
! An include file rather than a module, so that no .mod file has to be shipped
! and any Fortran compiler can consume it:
!
!   program my_prog
!     use iso_c_binding
!     implicit none
!     include 'smc.f90'    ! <- here, after implicit none
!     ...
!   end program
!
! Every C pointer is a  type(c_ptr), value  dummy argument.  Pass c_loc(x)
! for an array or a struct you own -- it must carry the target attribute --
! or c_null_ptr where the C interface accepts NULL.  The single exception is
! the void** out-parameter of smc_coloring, declared type(c_ptr),
! intent(out), which receives the opaque result handle.
!
! Dense matrices are column-major, which is already Fortran's own layout, so
! a 2D array can be handed over directly with c_loc.  Buffer lengths are
! element counts, never byte counts.

  ! Version
  integer(c_int), parameter :: SMC_VERSION_MAJOR = 0
  integer(c_int), parameter :: SMC_VERSION_MINOR = 4
  integer(c_int), parameter :: SMC_VERSION_PATCH = 27

  ! -------------------------------------------------------------------------
  ! Enumerators  (must match smc.h)
  ! -------------------------------------------------------------------------

  ! SmcDataType
  ! Element type of the numerical buffers passed to smc_compress and
  ! smc_decompress (double or float).  The sparsity pattern is always int.
  integer(c_int), parameter :: SMC_FLOAT64 = 0
  integer(c_int), parameter :: SMC_FLOAT32 = 1

  ! SmcStructure
  ! Structure of the matrix.  SMC_SYMMETRIC states that the sparsity pattern
  ! is symmetric and selects the symmetric coloring problems.
  integer(c_int), parameter :: SMC_NONSYMMETRIC = 0
  integer(c_int), parameter :: SMC_SYMMETRIC    = 1

  ! SmcPartition
  ! Which dimension is colored.  SMC_BIDIRECTIONAL colors rows and columns at
  ! the same time and produces two compressed matrices.
  integer(c_int), parameter :: SMC_COLUMN        = 0
  integer(c_int), parameter :: SMC_ROW           = 1
  integer(c_int), parameter :: SMC_BIDIRECTIONAL = 2

  ! SmcDecompression
  ! How the nonzeros are recovered from the compressed matrix.
  ! SMC_SUBSTITUTION needs fewer colors but is only available for the
  ! symmetric-column and bidirectional problems.
  integer(c_int), parameter :: SMC_DIRECT       = 0
  integer(c_int), parameter :: SMC_SUBSTITUTION = 1

  ! SmcOrder
  ! Vertex order used by the greedy coloring algorithm.
  ! RandomOrder is deliberately not exposed by this interface.
  integer(c_int), parameter :: SMC_NATURAL               = 0
  integer(c_int), parameter :: SMC_LARGEST_FIRST         = 1
  integer(c_int), parameter :: SMC_SMALLEST_LAST         = 2
  integer(c_int), parameter :: SMC_INCIDENCE_DEGREE      = 3
  integer(c_int), parameter :: SMC_DYNAMIC_LARGEST_FIRST = 4

  ! -------------------------------------------------------------------------
  ! Coloring options  (must match the struct in smc.h)
  !
  ! Passed to smc_coloring and smc_fast_coloring as c_loc(opts), and
  ! remembered by the result handle.  Initialise with smc_default_options()
  ! before overriding individual fields; c_null_ptr means the defaults.
  !
  ! Supported (structure, partition, decompression) combinations; anything
  ! else is rejected with -2:
  !   SMC_NONSYMMETRIC SMC_COLUMN        SMC_DIRECT
  !   SMC_NONSYMMETRIC SMC_ROW           SMC_DIRECT
  !   SMC_SYMMETRIC    SMC_COLUMN        SMC_DIRECT
  !   SMC_SYMMETRIC    SMC_COLUMN        SMC_SUBSTITUTION
  !   SMC_NONSYMMETRIC SMC_BIDIRECTIONAL SMC_DIRECT
  !   SMC_NONSYMMETRIC SMC_BIDIRECTIONAL SMC_SUBSTITUTION
  ! -------------------------------------------------------------------------

  type, bind(c) :: SmcColoringOptions
    integer(c_int) :: structure          ! SmcStructure     - default SMC_NONSYMMETRIC
    integer(c_int) :: partition          ! SmcPartition     - default SMC_COLUMN
    integer(c_int) :: decompression      ! SmcDecompression - default SMC_DIRECT
    integer(c_int) :: order              ! SmcOrder         - default SMC_NATURAL
    integer(c_int) :: postprocessing     ! 0/1 - give the neutral color 0 to the entries that need no
                                         !       evaluation, where possible (default 0)
    integer(c_int) :: symmetric_pattern  ! 0/1 - assert that the sparsity pattern is symmetric,
                                         !       skipping the symmetrization step (default 0)
    integer(c_int) :: index_base         ! 0 or 1 - index base of colptr, rowval and of the group
                                         !          members returned by the queries (default 0)
    integer(c_int) :: dtype              ! SmcDataType - element type used by smc_compress and
                                         !               smc_decompress (default SMC_FLOAT64)
  end type SmcColoringOptions

  ! -------------------------------------------------------------------------
  ! Return codes
  !
  ! Every function returning integer(c_int) returns one of:
  !
  !    0  success
  !   -1  internal error (a Julia exception was caught and logged)
  !   -2  unsupported combination of (structure, partition, decompression,
  !       dtype)
  !   -3  invalid argument (NULL pointer, bad dimension, buffer too small,
  !       bad enum value, bad index_base)
  !   -4  invalid or already-freed handle
  ! -------------------------------------------------------------------------

  ! -------------------------------------------------------------------------
  ! C function interfaces
  ! -------------------------------------------------------------------------

  interface

    ! -------------------------------------------------------------------------
    ! smc_default_options
    !
    ! Return an SmcColoringOptions filled with the defaults: nonsymmetric
    ! structure, column partition, direct decompression, natural order, no
    ! postprocessing, no symmetric-pattern assertion, 0-based indices and
    ! SMC_FLOAT64.  Always start from this call, override the fields you
    ! need, then pass c_loc(opts).
    ! -------------------------------------------------------------------------
    function smc_default_options() &
        bind(c, name='smc_default_options') result(opts)
      import :: SmcColoringOptions
      type(SmcColoringOptions) :: opts
    end function smc_default_options

    ! -------------------------------------------------------------------------
    ! smc_version
    !
    ! Write the SparseMatrixColorings.jl version of this library into major,
    ! minor and patch (the same values as the SMC_VERSION_* parameters).
    ! Pass c_loc of three integer(c_int), target scalars.
    ! -------------------------------------------------------------------------
    subroutine smc_version(major, minor, patch) &
        bind(c, name='smc_version')
      use iso_c_binding
      integer(c_int), intent(out) :: major, minor, patch
    end subroutine smc_version

    ! -------------------------------------------------------------------------
    ! Coloring
    !
    ! The pattern is always given in CSC form, in opts%index_base.  The
    ! caller's arrays are copied and never modified.
    ! -------------------------------------------------------------------------

    ! -------------------------------------------------------------------------
    ! smc_coloring
    !
    ! Color the m-by-n sparsity pattern given in CSC form and return an
    ! opaque result handle through result_out.
    !   m, n       : number of rows and columns, both > 0
    !   colptr     : c_loc of n+1 column pointers, in opts%index_base
    !   rowval     : c_loc of the row indices of the nonzeros, in
    !                opts%index_base, length colptr(n+1) - colptr(1)
    !   opts       : c_loc(options), or c_null_ptr for the defaults
    !   result_out : receives the handle; release it with smc_result_free
    ! Returns 0, -1 internal error, -2 unsupported combination, -3 invalid
    ! argument.
    ! -------------------------------------------------------------------------
    function smc_coloring(m, n, colptr, rowval, opts, result_out) &
        bind(c, name='smc_coloring') result(ret)
      use iso_c_binding
      integer(c_int), value       :: m, n
      type(c_ptr),    value       :: colptr, rowval, opts
      type(c_ptr),    intent(out) :: result_out
      integer(c_int)              :: ret
    end function smc_coloring

    ! -------------------------------------------------------------------------
    ! smc_fast_coloring
    !
    ! Color the pattern and write the colors directly, without allocating a
    ! handle.  The groups and the compression helpers need smc_coloring.
    !   row_colors    : c_loc of a length-m buffer, c_null_ptr when the
    !                   partition produces no row coloring (SMC_COLUMN)
    !   column_colors : c_loc of a length-n buffer, c_null_ptr when the
    !                   partition produces no column coloring (SMC_ROW)
    !   ncolors_out   : c_loc of a scalar receiving the number of colors
    ! SMC_BIDIRECTIONAL fills both buffers, so neither may be c_null_ptr.
    ! Colors are labels in 1..ncolors; 0 marks an entry that needs no
    ! evaluation and can only appear when opts%postprocessing is 1.
    ! Returns 0, -1 internal error, -2 unsupported combination, -3 invalid
    ! argument.
    ! -------------------------------------------------------------------------
    function smc_fast_coloring(m, n, colptr, rowval, opts, row_colors, column_colors, &
                               ncolors_out) &
        bind(c, name='smc_fast_coloring') result(ret)
      use iso_c_binding
      integer(c_int), value :: m, n
      type(c_ptr),    value :: colptr, rowval, opts, row_colors, column_colors, ncolors_out
      integer(c_int)        :: ret
    end function smc_fast_coloring

    ! -------------------------------------------------------------------------
    ! smc_result_free
    !
    ! Release a handle returned by smc_coloring; it must not be used again.
    ! Returns 0, or -4 if the handle is unknown (freeing twice is safe).
    ! -------------------------------------------------------------------------
    function smc_result_free(result) &
        bind(c, name='smc_result_free') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result
      integer(c_int)     :: ret
    end function smc_result_free

    ! -------------------------------------------------------------------------
    ! Queries
    !
    ! All of them take a handle from smc_coloring.  Every buffer crossing
    ! the interface carries its own length, that length is checked before a
    ! single element is read or written, and every sizing question has a
    ! query, so a caller can always ask before allocating:
    !
    !   buffer   length argument   how to obtain the required length
    !   colors   len               n (columns) or m (rows), from smc_size
    !   members  len               smc_column_group_size / smc_row_group_size
    !   nzval    nzval_len         smc_nnz
    !   Bc       Bc_len            Bc_rows*Bc_cols, smc_compressed_size
    !   Br       Br_len            Br_rows*Br_cols, smc_compressed_size
    !   A_out    A_len             m*n, from smc_size
    !
    ! Lengths are element counts, never byte counts.  The numerical
    ! buffers use size_t rather than int because A_len is m*n, which
    ! overflows a 32-bit int.  Too small a buffer is rejected with -3.
    ! -------------------------------------------------------------------------

    ! -------------------------------------------------------------------------
    ! smc_ncolors
    !
    ! Write the total number of colors into the scalar pointed to by
    ! ncolors_out.  Returns 0, -3 invalid argument, -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_ncolors(result, ncolors_out) &
        bind(c, name='smc_ncolors') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result, ncolors_out
      integer(c_int)     :: ret
    end function smc_ncolors

    ! -------------------------------------------------------------------------
    ! smc_column_colors
    !
    ! Copy the color of every column into colors; len must be at least n.
    ! Colors are labels in 1..ncolors, 0 meaning "no evaluation needed".
    ! Returns 0, -2 if the partition has no column coloring, -3 invalid
    ! argument (including len < n), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_column_colors(result, colors, len) &
        bind(c, name='smc_column_colors') result(ret)
      use iso_c_binding
      type(c_ptr),    value :: result, colors
      integer(c_int), value :: len
      integer(c_int)        :: ret
    end function smc_column_colors

    ! -------------------------------------------------------------------------
    ! smc_row_colors
    !
    ! Copy the color of every row into colors; len must be at least m.
    ! Colors are labels in 1..ncolors, 0 meaning "no evaluation needed".
    ! Returns 0, -2 if the partition has no row coloring, -3 invalid
    ! argument (including len < m), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_row_colors(result, colors, len) &
        bind(c, name='smc_row_colors') result(ret)
      use iso_c_binding
      type(c_ptr),    value :: result, colors
      integer(c_int), value :: len
      integer(c_int)        :: ret
    end function smc_row_colors

    ! -------------------------------------------------------------------------
    ! smc_ncolumn_groups
    !
    ! Write the number of column groups into ngroups_out.  Groups are the
    ! color classes: group g holds every column colored g.
    ! Returns 0, -2 if the partition has no column coloring, -3 invalid
    ! argument, -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_ncolumn_groups(result, ngroups_out) &
        bind(c, name='smc_ncolumn_groups') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result, ngroups_out
      integer(c_int)     :: ret
    end function smc_ncolumn_groups

    ! -------------------------------------------------------------------------
    ! smc_nrow_groups
    !
    ! Write the number of row groups into ngroups_out.
    ! Returns 0, -2 if the partition has no row coloring, -3 invalid
    ! argument, -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_nrow_groups(result, ngroups_out) &
        bind(c, name='smc_nrow_groups') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result, ngroups_out
      integer(c_int)     :: ret
    end function smc_nrow_groups

    ! -------------------------------------------------------------------------
    ! smc_column_group_size
    !
    ! Write the number of columns in column group `group` into size_out.
    ! `group` is 1-based and runs over 1..smc_ncolumn_groups, independently
    ! of opts%index_base.  Query the size first, then fetch the members.
    ! Returns 0, -2 if the partition has no column coloring, -3 invalid
    ! argument (including an out-of-range group), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_column_group_size(result, group, size_out) &
        bind(c, name='smc_column_group_size') result(ret)
      use iso_c_binding
      type(c_ptr),    value :: result
      integer(c_int), value :: group
      type(c_ptr),    value :: size_out
      integer(c_int)        :: ret
    end function smc_column_group_size

    ! -------------------------------------------------------------------------
    ! smc_column_group
    !
    ! Copy the column indices of column group `group` into members; len must
    ! be at least smc_column_group_size(result, group, ...).  The indices are
    ! written in opts%index_base.
    ! Returns 0, -2 if the partition has no column coloring, -3 invalid
    ! argument (including len too small), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_column_group(result, group, members, len) &
        bind(c, name='smc_column_group') result(ret)
      use iso_c_binding
      type(c_ptr),    value :: result
      integer(c_int), value :: group
      type(c_ptr),    value :: members
      integer(c_int), value :: len
      integer(c_int)        :: ret
    end function smc_column_group

    ! -------------------------------------------------------------------------
    ! smc_row_group_size
    !
    ! Write the number of rows in row group `group` into size_out.  `group`
    ! is 1-based and runs over 1..smc_nrow_groups.
    ! Returns 0, -2 if the partition has no row coloring, -3 invalid
    ! argument (including an out-of-range group), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_row_group_size(result, group, size_out) &
        bind(c, name='smc_row_group_size') result(ret)
      use iso_c_binding
      type(c_ptr),    value :: result
      integer(c_int), value :: group
      type(c_ptr),    value :: size_out
      integer(c_int)        :: ret
    end function smc_row_group_size

    ! -------------------------------------------------------------------------
    ! smc_row_group
    !
    ! Copy the row indices of row group `group` into members; len must be at
    ! least smc_row_group_size(result, group, ...).  The indices are written
    ! in opts%index_base.
    ! Returns 0, -2 if the partition has no row coloring, -3 invalid
    ! argument (including len too small), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_row_group(result, group, members, len) &
        bind(c, name='smc_row_group') result(ret)
      use iso_c_binding
      type(c_ptr),    value :: result
      integer(c_int), value :: group
      type(c_ptr),    value :: members
      integer(c_int), value :: len
      integer(c_int)        :: ret
    end function smc_row_group

    ! -------------------------------------------------------------------------
    ! smc_nnz
    !
    ! Write the number of stored entries of the sparsity pattern this result
    ! was built from into nnz_out.  That is exactly the required nzval_len
    ! of smc_compress.
    ! Returns 0, -3 invalid argument, -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_nnz(result, nnz_out) &
        bind(c, name='smc_nnz') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result, nnz_out
      integer(c_int)     :: ret
    end function smc_nnz

    ! -------------------------------------------------------------------------
    ! smc_size
    !
    ! Write the dimensions of the matrix this result was built from into
    ! m_out and n_out: the lengths expected by smc_row_colors (m) and
    ! smc_column_colors (n), and A_len must be at least m*n.
    ! Both pointers must be non-NULL.
    ! Returns 0, -3 invalid argument, -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_size(result, m_out, n_out) &
        bind(c, name='smc_size') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result, m_out, n_out
      integer(c_int)     :: ret
    end function smc_size

    ! -------------------------------------------------------------------------
    ! Compression / decompression
    !
    ! Dense matrices are column-major (Fortran / Julia order) and hold
    ! double or float elements according to opts%dtype.
    ! -------------------------------------------------------------------------

    ! -------------------------------------------------------------------------
    ! smc_compressed_size
    !
    ! Report the dimensions of the compressed matrices, so the caller can
    ! size the buffers of smc_compress and smc_decompress.
    !   Bc : m-by-ncolors for a column partition, ncolors-by-n for a row
    !        partition, m-by-ncolumn_groups for a bidirectional one
    !   Br : nrow_groups-by-n, used only by SMC_BIDIRECTIONAL; for the other
    !        partitions Br_rows and Br_cols are set to 0
    ! All four pointers must be non-NULL.
    ! Returns 0, -3 invalid argument, -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_compressed_size(result, Br_rows, Br_cols, Bc_rows, Bc_cols) &
        bind(c, name='smc_compressed_size') result(ret)
      use iso_c_binding
      type(c_ptr), value :: result, Br_rows, Br_cols, Bc_rows, Bc_cols
      integer(c_int)     :: ret
    end function smc_compressed_size

    ! -------------------------------------------------------------------------
    ! smc_compress
    !
    ! Compress the matrix into the dense buffers Br and Bc.  Every buffer is
    ! followed by its length, counted in elements of the type selected by
    ! opts%dtype -- never in bytes.
    !   nzval, nzval_len : c_loc of the CSC values, in the same order as the
    !                      rowval given to smc_coloring, real(c_double) or
    !                      real(c_float) according to opts%dtype; nzval_len
    !                      at least smc_nnz
    !   Br, Br_len       : row-compressed matrix, used only by
    !                      SMC_BIDIRECTIONAL; otherwise c_null_ptr and 0
    !   Bc, Bc_len       : column-compressed matrix, at least Bc_rows*Bc_cols
    ! Both buffers are column-major with the dimensions reported by
    ! smc_compressed_size, which is Fortran's own layout: B(i,j).
    ! Returns 0, -1 internal error, -3 invalid argument (a c_null_ptr the
    ! partition needs, or a buffer too small), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_compress(result, nzval, nzval_len, Br, Br_len, Bc, Bc_len) &
        bind(c, name='smc_compress') result(ret)
      use iso_c_binding
      type(c_ptr),       value :: result, nzval
      integer(c_size_t), value :: nzval_len
      type(c_ptr),       value :: Br
      integer(c_size_t), value :: Br_len
      type(c_ptr),       value :: Bc
      integer(c_size_t), value :: Bc_len
      integer(c_int)           :: ret
    end function smc_compress

    ! -------------------------------------------------------------------------
    ! smc_decompress
    !
    ! Recover the full m-by-n dense matrix from the compressed form.  Every
    ! buffer is followed by its length, counted in elements of the type
    ! selected by opts%dtype -- never in bytes.
    !   Br, Br_len   : the buffer filled by smc_compress, used only by
    !                  SMC_BIDIRECTIONAL; otherwise c_null_ptr and 0
    !   Bc, Bc_len   : the buffer filled by smc_compress, at least
    !                  Bc_rows*Bc_cols from smc_compressed_size
    !   A_out, A_len : m*n elements, column-major, of the type selected by
    !                  opts%dtype; A_len at least m*n, with m and n from
    !                  smc_size
    ! Entries outside the sparsity pattern are set to zero.
    ! Returns 0, -1 internal error, -3 invalid argument (a c_null_ptr the
    ! partition needs, or a buffer too small), -4 invalid handle.
    ! -------------------------------------------------------------------------
    function smc_decompress(result, Br, Br_len, Bc, Bc_len, A_out, A_len) &
        bind(c, name='smc_decompress') result(ret)
      use iso_c_binding
      type(c_ptr),       value :: result, Br
      integer(c_size_t), value :: Br_len
      type(c_ptr),       value :: Bc
      integer(c_size_t), value :: Bc_len
      type(c_ptr),       value :: A_out
      integer(c_size_t), value :: A_len
      integer(c_int)           :: ret
    end function smc_decompress

  end interface
